### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Unibozu** [uxcam/cordova-uxcam#1]
Hey Guys,

There is a typo in the documentation or the code : the method `tagUserName` is actually named `tagUsersName`

https://github.com/uxcam/cordova-uxcam/blob/master/www/UXCam.js#L35

Cheers !

**Comment by richardgroves** [comment]
Thank you - it was the documentation that was wrong. Fixed in a2109a5c5c8c86ea8fe727e54e398d57beeb7687
