### ISSUE TITLE
Plugin not compatible with cordova-android >= 7.0.0

### ISSUE THREAD

**Issue by Nico924** [uxcam/cordova-uxcam#11]
If I install the plugin on a cordova-app with cordova-android  version >= 7.0.0 I get the following : 

deviceready has not fired after 5 seconds.
then a list of "Channel not fired" : 
Channel not fired: onCordovaInfoReady
Channel not fired: onFileSystemPathsReady
(this list depend on the other plugins installed)

**Comment by LaloCastilla** [comment]
same here

**Comment by bishwash-adhikari** [comment]
@LaloCastilla which branch are you working with? Could you please try our latest change on branch 3.0.0-beta.1.

**Comment by LaloCastilla** [comment]
Hi @bishwash72, i was using the 2.3.6 branch but then i upgraded to 3.0.0-beta.1. with no results either, im using cordova android platform 7.0.0. 

in the ready() funtion of ionic im executing it like this:

`window["UXCam"].startWithKey('d9f707635967f38', function () { alert('start ssss') }, function () { alert('start error') });`

The error prints: Class not found. 

Hope you guys can help!

**Comment by bishwash-adhikari** [comment]
Here is the snippet from app.component.ts file from our sample app. Could you try this. Declaring the var first and then calling UXCam `declare var UXCam:any;`
```
import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';

import { TabsPage } from '../pages/tabs/tabs';
declare var UXCam:any;

@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  rootPage:any = TabsPage;

  constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen) {
    platform.ready().then(() => {
      console.log('UXCam on platform ready');
      UXCam.startWithKey('APP_KEY');
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      statusBar.styleDefault();
      splashScreen.hide();
    });
  }
}

```

**Comment by LaloCastilla** [comment]
Hi, thanks for your attention. I have been testing with your sample project provided by this url:
https://drive.google.com/file/d/1i4SYBQaTpPfZ4mKoAOcHn_d50d_DpUaa/view

But i am having the same result. 

The error prints: Class not found.


`
import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';

import { TabsPage } from '../pages/tabs/tabs';

declare var UXCam:any;


@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  rootPage:any = TabsPage;

  constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen) {
    platform.ready().then(() => {

      UXCam.startWithKey('d9f707635967f38', function () { alert('start ssss') }, function () { alert('start error') });

      statusBar.styleDefault();

      splashScreen.hide();

    });
  }
}
`




This our ionic info:

√ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)  : 4.1.1 (C:\Users\Eduardo\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.8

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : not available
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.0.5, cordova-plugin-ionic-webview 1.2.0, (and 4 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\Eduardo\AppData\Local\Android\Sdk)
   NodeJS            : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm               : 5.10.0
   OS                : Windows 1


Hope you guys can help our company to integrate this product.

**Comment by kveber** [comment]
anyone get some feedback about this error or found some alternative?
