### ISSUE TITLE
optIn/optOut does not seem to work consistently

### ISSUE THREAD

**Issue by ciekawy** [uxcam/cordova-uxcam#15]
- `optInStatus()` initially reports always `true` - thats ok

- after calling `optOut()`, `optInStatus()` reports `false` - thats also ok
- calling `optIn()` reports success but `optInStatus()` reports `false` - I see no way to `optIn` back after `optOut`

**Comment by susanuxcam** [comment]
Hey @ciekawy, I'm sorry for such a late reply! I've just sent this issue to our engineering team and we will come back to you shortly

**Comment by susanuxcam** [comment]
Hi again @ciekawy! Can you try to update SDK to the most recent version? This should help!

If you're still getting this error, can you tell me if it happens on Android, iOS or both?

**Comment by susanuxcam** [comment]
hey @ciekawy, have you had a chance to test the most recent UXCam SDK version?
