### ISSUE TITLE
Encountering error: UXCam.occludeRectsOnNextFrame is not a function

### ISSUE THREAD

**Issue by CJZamora83** [uxcam/cordova-uxcam#19]
Hi:
  _UXCam.occludeRectsOnNextFrame is not a function_ error occurs when a user, on one of our internal native Android apps, accesses an endpoint that opens another internal web app in Android Chrome.  This only happens on Android, not in Chrome for iOS nor is this error logged when a user is solely using our web app in any browser.  This error occurrence is exclusive for Android and Chrome.  This error does not break anything; the user experience is completely intact but it's an error that I've looked at and can't seem to figure out.

(I'm not showing any code so as to not get in trouble but I figured maybe someone can point me in the right direction)

**Comment by susanuxcam** [comment]
Hey @CJZamora83, thanks for reporting this! Can you tell me which SDK version you're using?

**Comment by CJZamora83** [comment]
@susanuxcam  Thanks for replying.  We support API Level 21 - 28.

**Comment by susanuxcam** [comment]
hey again @CJZamora83! And could you tell me which UXCam SDK version you're using?

**Comment by CJZamora83** [comment]
@susanuxcam 3.1.11

**Comment by susanuxcam** [comment]
Thanks, we will try to replicate the error and I'll keep you posted!

**Comment by susanuxcam** [comment]
Hey @CJZamora83, we were able to replicate the issue and we'll be working on the solution. I'll keep you updated!

**Comment by susanuxcam** [comment]
hey @CJZamora83, the issue should be fixed in version 3.2.1. Could you update your SDK?

**Comment by CJZamora83** [comment]
@susanuxcam we definitely will.  Thanks for your attention and updating.  Take care.
