### ISSUE TITLE
Cordova plugin occludeSensitiveView()

### ISSUE THREAD

**Issue by Unibozu** [uxcam/cordova-uxcam#2]
Hi guys,

Is there a way to hide sensitive information when using your Cordova plugin ? I've seen `occludeSensitiveView` on your iOS/Android documentation (on your website) but it doesn't seem  available for the Cordova integration ?

Maybe there is a way around then ?

Cheers

**Comment by richardgroves** [comment]
Hi,

We're working on a way to hide the whole screen from Cordova - should be available for testing in a day or two. I'll update this issue with details when available.

**Comment by richardgroves** [comment]
Hi @Unibozu 

We've got the next version ready for testing that includes the occludeScreen functionality.

If you want to test it out remove the current UXCam plugin and then at the command line:

cordova plugins add https://github.com/uxcam/cordova-uxcam.git

will install this test version. Once we complete testing and confirm all is ok we'll push it to the official registry as version 2.2.0. If you try it out please let me know how you get on.

Thanks,
Richard

**Comment by richardgroves** [comment]
This update is now live in the plugin registry so a normal:

cordova plugins add com.uxcam.cordova.plugin

will get the latest version - v2.2.0 - now.
