### ISSUE TITLE
setUserProperty method missing?

### ISSUE THREAD

**Issue by pghmatt** [uxcam/cordova-uxcam#21]
We're trying to send additional user information to UXCam from our Cordova project using version 3.2.2 of this plugin and we're testing under iOS.  We're getting the error ERROR: Method 'setUserProperty:' not defined in Plugin 'UXCam' when we try to call UXCam.setUserProperty('envName', config.envName).  I checked the plugin source at CDVUXCam.m, the header CDVUXCam.h and there is no method in there named setUserProperty...  In UXCam.js the method is defined though.

**Comment by susanuxcam** [comment]
Hey @pghmatt, we will fix this issue in the upcoming release. I will let you know as soon as it's live. I'm sorry about the hassle!

**Comment by pghmatt** [comment]
Thanks @susanuxcam do you have an ETA for the release?

**Comment by susanuxcam** [comment]
Hey! We expect to have it within 2 weeks. I will keep you posted!

**Comment by susanuxcam** [comment]
Hey @pghmatt, we've just released the new version 3.3.0 with the fix. Can you test it out?
