### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by cerealexx** [uxcam/cordova-uxcam#22]
There is a noticeable frame skipping every second. My clue is that this is related to the taken screenshots.
Is there a way to deactivate the video recording and only send raw data?

**Comment by cerealexx** [comment]
Nevermind, it can be done with `occludeSensitiveScreen(true)` at the start.

**Comment by richardgroves** [comment]
@cerealexx You can also disable video recording on the Record Settings page on the dashboard.
