### ISSUE TITLE
Screens are not capturing

### ISSUE THREAD

**Issue by asangadev** [uxcam/cordova-uxcam#24]
Hi team,

We are testing the UXCAM and everything seems working well except the **screens**. 

Is this something to do with WKWebView permissions? Please advise.

We are testing with one screen at this stage:

`UXCam.setAutomaticScreenNameTagging(false);`
`UXCam.tagScreenName("HomeScreen");`

<img width="345" alt="Screen Shot 2020-08-08 at 8 07 50 am" src="https://user-images.githubusercontent.com/16328655/89692200-64cc2b80-d94e-11ea-85c0-6137bf85986c.png">

**Comment by asangadev** [comment]
I have also set up this blank project: [github.com/asangadev/screens](https://github.com/asangadev/screens)

**Comment by susanuxcam** [comment]
Hey @asangadev, I've already got back to you regarding this on our chat!

**Comment by asangadev** [comment]
@susanuxcam 

This needs to look like this.

![temp](https://user-images.githubusercontent.com/16328655/89772517-76c3ef00-db45-11ea-8838-f55321a90a9f.jpg)

**Comment by susanuxcam** [comment]
Hey @asangadev, the issue has been fixed globally by our developers

**Comment by asangadev** [comment]
@susanuxcam Thanks for the prompt action. It's working for us now.
