### ISSUE TITLE
iOS - Crashed: com.uxcam.UXPlistHandler.workQ

### ISSUE THREAD

**Issue by liviu0406** [uxcam/cordova-uxcam#25]
Hello,
Starting with iOS 14, UXCam registered some crashes on UXPlistHandler. The number of impacted users is growing day by day. 

Affected OS: 14.0, 14.0.1, 14.2
UXCam version: 3.2.6.

<img width="1062" alt="Screenshot 2020-10-07 at 12 38 26" src="https://user-images.githubusercontent.com/72495738/95314870-7c665880-089a-11eb-8ef1-0d97ba14f11f.png">
<img width="845" alt="Screenshot 2020-10-07 at 12 37 46" src="https://user-images.githubusercontent.com/72495738/95314888-80927600-089a-11eb-817f-5382d5cbddb1.png">

Thanks,
Liviu

**Comment by susanuxcam** [comment]
Hey @liviu0406, I will report it to our developers. Could you tell me how often you're getting this crash?

**Comment by liviu0406** [comment]
Hi @susanuxcam, so far the crash impacts 2-3 users per day (1 crash/user), but the impact will be greater once more users will update to iOS 14 or greater.

**Comment by susanuxcam** [comment]
@liviu0406 thanks! can you also tell me how many users a day you have on iOS 14 so that we know what's the frequency of the crashes?

**Comment by liviu0406** [comment]
@susanuxcam, we have about 120 active users per day with iOS 14 and greater.

**Comment by susanuxcam** [comment]
thanks @liviu0406, our developers will investigate it and I will keep you posted!

**Comment by susanuxcam** [comment]
Hey @liviu0406! Our developers would like to get in touch with you directly so I will invite you to our slack community to discuss the issue with you there. I hope it works for you!

**Comment by liviu0406** [comment]
Hi @susanuxcam! Sure. Do you need an e-mail address from my side or we'll use an invite link?

**Comment by susanuxcam** [comment]
Hey @liviu0406 I think I've already found it :) You can log in here as your account already exists there: mobile-app-experts.slack.com

**Comment by RedJhon21** [comment]
@susanuxcam @liviu0406  hello , I'm facing the same crash for iOS 14 users , would you tell how you clear it .

**Comment by richardgroves** [comment]
Hi @RedJhon21 

Sorry to hear about the problem. We've been trying to track it down - can you contact our Customer Success team so they can share some information with me to help diagnose it in your case.

Our current thinking is that it is partly due to a bug in iOS14 - this code is inside a try/catch block which should mean any exception is caught - but also something in our data file is triggering a bad path in the OS code.

Richard

**Comment by RedJhon21** [comment]
@richardgroves thanks for the quick response , I did contact your customer success , hoping to clear this issue

**Comment by DFDIEGOH** [comment]
Can you please update the Cordova SDK to version 3.4.3 and check if you are getting the same crash? @RedJhon21 @liviu0406
