### ISSUE TITLE
[UXCamHandler finishBackgroundTask]   Processing timeout resulted in being killed by the system.  Too many crashes

### ISSUE THREAD

**Issue by hzh137940556** [uxcam/cordova-uxcam#26]
Hope to fix it as soon as possible and give a reply. thank you very much

_55-[UXPlistHandler uploadSingleFileCompleted:parameters:]_block_invoke (UXPlistHandler.m:1896)

_34-[UXPlistHandler reverifySession:]_block_invoke_3 (UXPlistHandler.m:1733)

+[UXUtil settings] (UXUtil.m:377)

crash:1 
I printed logs through metric and found that many logs were killed due to timeout of background tasks. After shielding UXCam, this situation disappears.

crash2
![image](https://user-images.githubusercontent.com/15024810/110721311-45321400-824b-11eb-9cd6-a92ff977735c.png)

crash3 
![image](https://user-images.githubusercontent.com/15024810/110721333-4feca900-824b-11eb-8a9b-1f1e9c94736e.png)

thank you very much

**Comment by hzh137940556** [comment]
@Bishwash-uxcam

**Comment by DFDIEGOH** [comment]
Hi there Diego here,
Can you please tell me which version of the IOS SDK are you using?

**Comment by hzh137940556** [comment]
@DFDIEGOH  
Sorry, I am using iOS-SDK, I submitted a question to this wrong place。
![image](https://user-images.githubusercontent.com/15024810/111863413-635bea80-8996-11eb-8334-a96a91247b05.png)

**Comment by DFDIEGOH** [comment]
Hi there, can you please update the SDK to version 3.3.3 and try to see if the errors still persist? Please let me know if everything works properly from your end 😄
