### ISSUE TITLE
CORDOVA CRASH

### ISSUE THREAD

**Issue by budafly** [uxcam/cordova-uxcam#31]
As soon I fire UXCam.startWithKey it crashes the app, Im testing from android emulator and a proper device, Im using version 3.5.1 Of UXCam

**Comment by Anup-UXCam** [comment]
Hi @budafly, can you share the stack trace with us?

Also, can you check with the latest version? Thanks!

**Comment by DFDIEGOH** [comment]
Close due to inactivity
