### ISSUE TITLE
urlForCurrentSession and urlForCurrentUser result in 404 Error

### ISSUE THREAD

**Issue by mike-sfr3** [uxcam/cordova-uxcam#38]
Hello! 

I'm hoping to use the `urForCurrentSession()` and `urlForCurrentUser()` methods to link our UXCam sessions with our app logs. I do get a value from these. It looks like: `uxc.am/s/xxxxxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxx`. However whenever I follow the link I always am greeted with a 404 Error page. 

Is there something I need to do to get these links to work correctly? Any help would be appreciated.

**Comment by mike-sfr3** [comment]
Looks like they eventually turn into working links. Do you have any information for how long that takes to happen?

**Comment by DFDIEGOH** [comment]
Hey @mike-sfr3 - This URLs get generated at the moment of verification of a session. In some cases, a session might take a couple of minutes to get uploaded to the dashboard, and this is the time where this URL becomes available, basically at the moment of session upload. 

Really glad that everything is working as expected now on your end, but don't hesitate reaching out in case you have any further questions.
