### ISSUE TITLE
urlForCurrentSession

### ISSUE THREAD

**Issue by fanals** [uxcam/cordova-uxcam#8]
Hi,

I wanted to associate crashlytics to uxcam as shown here https://uxcam.com/integrations/crashlytics

But urlForCurrentSession is not implemented and seems deprecated. Is there another way to do it using this plugin ?

Thanks

**Comment by uxcam-com** [comment]
on our test we didn't find issue with urlForCurrentSession. Example code :

```javascript
function onDeviceReady() {
    UXCam.startWithKey('UXCAM_APP_KEY', function () { console.log('start success') }, function () { console.log('start error') })

    UXCam.addVerificationListener(verificationSuccess);
}

function verificationSuccess() {
    UXCam.urlForCurrentUser(function(link){console.log('UXCam: User Recordings link '+ link)});
    UXCam.urlForCurrentSession(function(link){console.log('UXCam: Session Recording link '+ link)});
}
```

**Comment by fanals** [comment]
I'm on iOS and its not working for me :(

I updated to last version and used the example code but I have the error "Method 'addVerificationListener:' not defined in Plugin 'UXCam'"

If I remove addVerificationListener, set a timeout and call urlForCurrentSession I have nothing coming back from the callback.

In the plugin source code I see no method urlForCurrentSession: https://github.com/uxcam/cordova-uxcam/blob/master/src/ios/CDVUXCam.h

**Comment by richardgroves** [comment]
Apologies - the iOS and Android SDKs have diverged. We'll fix this and update you here when an updated plugin is available.

**Comment by k05h** [comment]
Hello. Any updates?

**Comment by richardgroves** [comment]
This should all be fixed now with the latest versions. Apologies for the delay.
