### ISSUE TITLE
setAutomaticScreenNameTagging

### ISSUE THREAD

**Issue by fanals** [uxcam/cordova-uxcam#9]
There is an encoding issue or an invisible special characters somewhere in function setAutomaticScreenNameTagging of the UXCam.js file

I had to rename variables successCallback and errorCallback. I was getting the error "Couldn't find successCallback"

**Comment by uxcam-com** [comment]
Thank you for reporting the issue. It has been fixed with latest commit. https://github.com/uxcam/cordova-uxcam/commit/117966d106915e44583fee181ec636d1edcac583

**Comment by richardgroves** [comment]
Version 2.3.6 of the plugin has been published now via npm
